NAME : A. VARSHITHA


REGISTRATION NO: 21BCE9406

ASSIGNMENT-1

Task 1 : Creating Dataframe(DataFrame name as 'df') with numpy random values(4 features and 4 observations)

In [22]:
import numpy as np
import pandas as pd

In [23]:
data=np.random.rand(4,4)
df=pd.DataFrame(data,columns=['Feature1','Feature2','Feature3','Feature4'])
df

   Feature1  Feature2  Feature3  Feature4
0  0.481872  0.179331  0.350468  0.600648
1  0.277844  0.043566  0.581615  0.817185
2  0.646480  0.498046  0.719409  0.599807
3  0.956658  0.188866  0.165767  0.737868

Task-2: Rename the task-1 'df'dataframe column names to 'Random vale 1','Random value 2','Random value 3'&'Random value 4'

In [24]:
new_column_names=['Random vale 1','Random value 2','Random value 3','Random value 4']
df.columns=new_column_names
df

   Random vale 1  Random value 2  Random value 3  Random value 4
0       0.481872        0.179331        0.350468        0.600648
1       0.277844        0.043566        0.581615        0.817185
2       0.646480        0.498046        0.719409        0.599807
3       0.956658        0.188866        0.165767        0.737868

Task-3: Find the descriptive statistics of the 'df' dataframe

In [25]:
df.describe()

       Random vale 1  Random value 2  Random value 3  Random value 4
count       4.000000        4.000000        4.000000        4.000000
mean        0.590714        0.227452        0.454315        0.688877
std         0.286798        0.192215        0.245305        0.107364
min         0.277844        0.043566        0.165767        0.599807
25%         0.430865        0.145390        0.304293        0.600438
50%         0.564176        0.184099        0.466041        0.669258
75%         0.724024        0.266161        0.616063        0.757697
max         0.956658        0.498046        0.719409        0.817185

Task-4: Check for the null values in'df' and find the data type of the column

In [26]:
df.isnull().any()

Random vale 1     False
Random value 2    False
Random value 3    False
Random value 4    False
dtype: bool

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Random vale 1   4 non-null      float64
 1   Random value 2  4 non-null      float64
 2   Random value 3  4 non-null      float64
 3   Random value 4  4 non-null      float64
dtypes: float64(4)
memory usage: 256.0 bytes

Task-5: Display the 'Random value 2' & 'Random value 3' columns with location method and index location method

In [28]:
df.loc[:,'Random value 2' : 'Random value 3']

   Random value 2  Random value 3
0        0.179331        0.350468
1        0.043566        0.581615
2        0.498046        0.719409
3        0.188866        0.165767

In [29]:
df.iloc[: ,1:3]

   Random value 2  Random value 3
0        0.179331        0.350468
1        0.043566        0.581615
2        0.498046        0.719409
3        0.188866        0.165767